Repository wecode-bootcamp-korea/11-WeStock-backend, pull requests merged in 2020-09, with the labels that each got.

#1 [westock 왕민욱] Refactor: 리뷰 반영 및 테이블 추가
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/models.py
  westock/settings.py
Labels: Status: 리뷰 요청

#2 [westock 이태현] Add: user app 생성 및 models.py 작성
  requirements.txt
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/validation.py
  user/views.py
  westock/settings.py
Labels: Status: Accepted

#3 [WeStock 왕민욱] Modify: Product의Models 수정
  product/migrations/0002_auto_20200903_0649.py
  product/models.py
Labels: Status: 리뷰 요청

#5 [WeStock 이충희] requirements.txt 재생성
  .gitignore
  requirements.txt
Labels: Status: 리뷰 요청

#4 [westock 이태현] Modified: Model 수정 및 Conflict 해결 완료 (requirements.txt 재해결했습니다.)
  requirements.txt
  user/migrations/0001_initial.py
  user/models.py
  user/urls.py
  westock/settings.py
  westock/urls.py
Labels: Status: 리뷰 요청

#6 [WeStock 이충희] Add: sale 앱의 모델 생성
  sale/__init__.py
  sale/admin.py
  sale/apps.py
  sale/migrations/0001_initial.py
  sale/migrations/__init__.py
  sale/models.py
  sale/tests.py
  sale/views.py
  westock/settings.py
Labels: Status: 리뷰 요청

#8 [WeStock 이충희] Modify: .gitignore 크롤링 데이터 관련 항목 추가
  .gitignore
Labels: Status: 리뷰 요청

#9 [WeStock 왕민욱] Modify: Product App의 Models 수정
  product/migrations/0003_auto_20200905_0750.py
  product/models.py
Labels: Status: 리뷰 요청

#10 [WeStock 왕민욱] Fix: Product App의 Models 수정
  product/models.py
Labels: Status: Accepted

#11 [WeStock 이충희] Add: 판매 페이지 상품 검색 뷰 & 유닛 테스트 생성
  sale/make_jsons.py
  sale/messages.py
  sale/tests.py
  sale/urls.py
  sale/views.py
  westock/urls.py
Labels: Status: Accepted

#12 [WeStock 이충희] Add: 구매 또는 판매 페이지에 맞는 상품 상세 정보 뷰 & 유닛테스트 생성
  sale/make_jsons.py
  sale/messages.py
  sale/tests.py
  sale/urls.py
  sale/utils.py
  sale/views.py
Labels: Status: 리뷰 요청

#14 [westock 이태현] Modified: Social Login 엔드포인트 KeyError 예외처리 추가 및 Follow 엔드포인트 로직 수정
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20200903_0649.py
  product/migrations/0003_auto_20200905_0750.py
  product/models.py
  sale/migrations/0001_initial.py
  user/migrations/0001_initial.py
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
  westock/settings.py
Labels: Status: Accepted

#15 Add: My Account Page Selling-list Endpoint
  user/tests.py
  user/urls.py
  user/views.py
  westock/settings.py
Labels: Status: 추가 기능 구현중

#16 [WeStock 이충희] Add: 구글 소셜 로그인 뷰 & 유닛 테스트
  requirements.txt
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#17 [WeStock 이충희] Add: Docker 세팅
  Dockerfile
  requirements.txt
  westock/settings.py
Labels: Status: 리뷰 요청

#18 [WeStock 이충희] Modify: 구글 로그인 뷰 오타 수정
  user/views.py
Labels: Status: 리뷰 요청

#13 [WeStock 왕민욱] Add: 제품 리스트 및 상세 페이지 관련 View 추가
  docker-compose.yml
  product/__init__.py
  product/admin.py
  product/apps.py
  product/tests.py
  product/urls.py
  product/views.py
  requirements.txt
  westock/settings.py
  westock/urls.py
Labels: Status: 리뷰 요청
